"""Build website data from the recorded Jev fixtures, so the site never shows invented numbers.

  frontend/assets/demo-data.js    the landing-page demo (weak → strong prompt)
  frontend/assets/api-example.json a real /v1/score response, shown in the API docs

Re-run after re-recording fixtures:  python scripts/build_demo_data.py
"""

import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tests.conftest import fixture_judge, load_fixture, make_router  # noqa: E402

from app.analyze import Analyzer  # noqa: E402
from app.config import load_config  # noqa: E402
from app.tokens import TokenCounter  # noqa: E402

ASSETS = ROOT.parent / "frontend" / "assets"


async def main() -> None:
    cfg = load_config(ROOT / "config")
    data = {}
    for name in ("weak", "strong"):
        fx = load_fixture(name)
        judge = fixture_judge(cfg, name)
        analyzer = Analyzer(router=make_router(cfg, judge), counter=TokenCounter(), config=cfg, cache_size=0)
        a = await analyzer.analyze(fx["prompt"])
        data[name] = {"prompt": fx["prompt"], "report": analyzer.web_report(a).model_dump(mode="json")}
        if name == "weak":
            example = analyzer.v1_response(
                a,
                request_id="req_example0000000000000000",
                include_suggestions=True,
                include_confidence=False,
                stored=False,
            )
            example_json = example.model_dump(mode="json", exclude_none=True)
            example_json["latency_ms"] = a.judged.answers.latency_ms  # the recorded Jev time, not the replay
            (ASSETS / "api-example.json").write_text(
                json.dumps({"request": {"prompt": fx["prompt"]}, "response": example_json}, indent=2) + "\n"
            )
        await judge.aclose()
    (ASSETS / "demo-data.js").write_text(
        "/* Generated by backend/scripts/build_demo_data.py from recorded Jev responses. Do not edit. */\n"
        f"window.PL_DEMO = {json.dumps(data, separators=(',', ':'))};\n"
    )
    w, s = data["weak"]["report"], data["strong"]["report"]
    print(
        f"demo: weak lint={w['lint_score']} pqs={w['pqs_score']} · strong lint={s['lint_score']} pqs={s['pqs_score']}"
    )
    print("wrote demo-data.js and api-example.json")


asyncio.run(main())
