"""Build frontend/assets/demo-data.js from the recorded Jev fixtures.

The landing-page demo replays these real analyses, so it never shows invented numbers.
Re-run after re-recording fixtures:  python scripts/build_demo_data.py
"""

import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tests.conftest import fixture_judge, load_fixture  # noqa: E402

from app.analyze import Analyzer  # noqa: E402
from app.config import load_config  # noqa: E402
from app.tokens import TokenCounter  # noqa: E402

OUT = ROOT.parent / "frontend" / "assets" / "demo-data.js"


async def main() -> None:
    cfg = load_config(ROOT / "config")
    data = {}
    for name in ("weak", "strong"):
        fx = load_fixture(name)
        judge = fixture_judge(cfg, name)
        report = await Analyzer(judge=judge, counter=TokenCounter(), config=cfg, cache_size=0).analyze(
            fx["prompt"]
        )
        data[name] = {"prompt": fx["prompt"], "report": report.model_dump(mode="json")}
        await judge.aclose()
    OUT.write_text(
        "/* Generated by backend/scripts/build_demo_data.py from recorded Jev responses. Do not edit. */\n"
        f"window.PL_DEMO = {json.dumps(data, separators=(',', ':'))};\n"
    )
    print(
        f"wrote {OUT.relative_to(ROOT.parent)}: weak={data['weak']['report']['lint_score']} strong={data['strong']['report']['lint_score']}"
    )


asyncio.run(main())
