"""accounts, api keys, usage

Revision ID: 0001
Revises:
Create Date: 2026-09-25 17:17:07.185599
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_prefix"), ["prefix"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "score_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("request_id", sa.String(length=40), nullable=False),
        sa.Column("key_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_chars", sa.Integer(), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("lint_score", sa.Integer(), nullable=False),
        sa.Column("pqs_score", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["key_id"], ["api_keys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("score_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_score_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_score_events_key_id"), ["key_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_score_events_request_id"), ["request_id"], unique=False)

    op.create_table(
        "usage_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("prompts", sa.Integer(), nullable=False),
        sa.Column("degraded", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["key_id"], ["api_keys.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_id", "day"),
    )
    with op.batch_alter_table("usage_daily", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usage_daily_day"), ["day"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_daily_key_id"), ["key_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_daily_user_id"), ["user_id"], unique=False)

    op.create_table(
        "stored_prompts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("event_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("system", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["score_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stored_prompts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stored_prompts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_stored_prompts_event_id"), ["event_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stored_prompts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stored_prompts_event_id"))
        batch_op.drop_index(batch_op.f("ix_stored_prompts_created_at"))

    op.drop_table("stored_prompts")
    with op.batch_alter_table("usage_daily", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_daily_user_id"))
        batch_op.drop_index(batch_op.f("ix_usage_daily_key_id"))
        batch_op.drop_index(batch_op.f("ix_usage_daily_day"))

    op.drop_table("usage_daily")
    with op.batch_alter_table("score_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_events_request_id"))
        batch_op.drop_index(batch_op.f("ix_score_events_key_id"))
        batch_op.drop_index(batch_op.f("ix_score_events_created_at"))

    op.drop_table("score_events")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_prefix"))

    op.drop_table("api_keys")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
